volumes:
  build_output:
  
services:
  gradle:
    image: gradle:7.6-jdk8
    volumes:
      - build_output:/home/gradle/project/build/dist
      - .:/home/gradle/project
    working_dir: /home/gradle/project
    command: ./gradlew war
    environment:
      - GRADLE_USER_HOME=/home/gradle/.gradle
  db:
    image: mysql/mysql-server:8.0.13
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hds
      MYSQL_USER: helpdesk
      MYSQL_PASSWORD: helpdesk
    command: --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - gradle
    volumes:
    - ./db:/docker-entrypoint-initdb.d

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"  # Web UI
      - "1025:1025"  # SMTP

  web:    
    depends_on:
      db:
        condition: service_healthy
      gradle:
        condition: service_completed_successfully
    volumes:
        - build_output:/tmp/build_output
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "80:8080"
    links:
      - db
      - maildev