type: specs.openrewrite.org/v1beta/recipe
name: com.bryanfriedman.hds.UpdateStrutsConfig
displayName: Update Struts config and web.xml
recipeList:
  # struts-config.xml edits
  - org.openrewrite.xml.RemoveXmlTag:
      fileMatcher: "src/**/struts-config.xml"
      xPath: "/struts-config/data-sources"
  - org.openrewrite.xml.AddOrUpdateChildTag:
      parentXPath: "/struts-config"
      newChildTag: <message-resources parameter="ApplicationResources" null="false"/>
  - org.openrewrite.text.FindAndReplace:
      filePattern: "src/**/struts-config.xml"
      find: "DTD Struts Configuration 1.0"
      replace: "DTD Struts Configuration 1.3"
  - org.openrewrite.text.FindAndReplace:
      filePattern: "src/**/struts-config.xml"
      find: "http://jakarta.apache.org/struts/dtds/struts-config_1_0"
      replace: "https://struts.apache.org/dtds/struts-config_1_3"

  - org.openrewrite.DeleteSourceFiles:
      filePattern: src/main/webapp/WEB-INF/*.tld

  # web.xml edits
  - org.openrewrite.xml.RemoveXmlTag:
      fileMatcher: "src/**/web.xml"
      xPath: "/web-app//taglib"
  - org.openrewrite.xml.AddOrUpdateChildTag:
      parentXPath: "/web-app"
      newChildTag: <security-role><role-name>A</role-name></security-role>
  - org.openrewrite.xml.AddOrUpdateChildTag:
      parentXPath: "/web-app"
      newChildTag: <security-role><role-name>L</role-name></security-role>
  - org.openrewrite.xml.AddOrUpdateChildTag:
      parentXPath: "/web-app"
      newChildTag: <security-role><role-name>S</role-name></security-role>